version: '3.8'
services:
  app:
    image: openjdk:21
    container_name: tastemanager-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Sao_Paulo